title: Oluwatoyin Olatunji
logo: headshot.jpeg
description: Data Analyst with a 4 years experience working across different sectors using Advance Excel for Report automation, Sql for data manipulation and interogation and Power Bi for creating business intelligent report.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
